# Generated by Django 4.2.16 on 2024-11-05 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.ForeignKey(db_column='file_upload', on_delete=django.db.models.deletion.CASCADE, related_name='file_permission', to='restapp.fileupload')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='user_file_permission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
