# Generated by Django 4.2.16 on 2024-11-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_filepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
