# Generated by Django 4.2.16 on 2024-11-05 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_alter_fileupload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepermission',
            name='file',
            field=models.ForeignKey(db_column='file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_permission', to='restapp.fileupload'),
        ),
        migrations.AlterField(
            model_name='filepermission',
            name='file_upload',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='filepermission',
            name='user',
            field=models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_file_permission', to=settings.AUTH_USER_MODEL),
        ),
    ]
