# Generated by Django 4.2.16 on 2024-11-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_filepermission_file_alter_filepermission_file_upload_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'permissions': [('can_read_file', 'Can read file'), ('can_write_file', 'Can write file')]},
        ),
    ]
