# Generated by Django 4.2.16 on 2024-11-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0007_alter_myusertable_options_myusertable_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={},
        ),
        migrations.AlterModelOptions(
            name='myusertable',
            options={},
        ),
        migrations.RemoveField(
            model_name='myusertable',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='myusertable',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myusertable',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='myusertable',
            name='user_permissions',
        ),
    ]
