# Generated by Django 4.2.16 on 2024-11-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0008_alter_fileupload_options_alter_myusertable_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepermission',
            name='file_upload',
        ),
    ]
